version: "3"
services:
  dasd:
    image: sheabot/daserver-dasd:alpine
    container_name: daserver-dasd
    restart: on-failure
    command: python /dasd/dasd --action start --cfg /dasd/dasd.cfg
    volumes:
      - ./dasd:/dasd:ro
      - ./ssh:/home/dasd/.ssh:ro
      - /mnt/sshfs:/mnt/sshfs:shared
      - /mnt/raid:/mnt/raid
